// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _201808202045043_PopulatingAddedValuesMovies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201808202045043_PopulatingAddedValuesMovies));
        
        string IMigrationMetadata.Id
        {
            get { return "201808231512240_201808202045043_PopulatingAddedValuesMovies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
